DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS todo;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fname VARCHAR(30) NOT NULL,
    lname VARCHAR(20) NOT NULL,
    dob DATE  NOT NULL,
    occupation TEXT NOT NULL,
    email VARCHAR(40) UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE todo(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    body VARCHAR(20) UNIQUE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);
